/*
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bymdev.voucherhub.model;

import java.util.Objects;
import com.bymdev.voucherhub.model.OrderItem;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GroupEntryDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T14:17:27.430+03:00")
public class GroupEntryDTO {
  @SerializedName("groupName")
  private String groupName = null;

  @SerializedName("items")
  private java.util.List<OrderItem> items = null;

  @SerializedName("voucherPerPerson")
  private Boolean voucherPerPerson = null;

  public GroupEntryDTO groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @ApiModelProperty(value = "")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public GroupEntryDTO items(java.util.List<OrderItem> items) {
    this.items = items;
    return this;
  }

  public GroupEntryDTO addItemsItem(OrderItem itemsItem) {
    if (this.items == null) {
      this.items = new java.util.ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @ApiModelProperty(value = "")
  public java.util.List<OrderItem> getItems() {
    return items;
  }

  public void setItems(java.util.List<OrderItem> items) {
    this.items = items;
  }

  public GroupEntryDTO voucherPerPerson(Boolean voucherPerPerson) {
    this.voucherPerPerson = voucherPerPerson;
    return this;
  }

   /**
   * Get voucherPerPerson
   * @return voucherPerPerson
  **/
  @ApiModelProperty(value = "")
  public Boolean isVoucherPerPerson() {
    return voucherPerPerson;
  }

  public void setVoucherPerPerson(Boolean voucherPerPerson) {
    this.voucherPerPerson = voucherPerPerson;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GroupEntryDTO groupEntryDTO = (GroupEntryDTO) o;
    return Objects.equals(this.groupName, groupEntryDTO.groupName) &&
        Objects.equals(this.items, groupEntryDTO.items) &&
        Objects.equals(this.voucherPerPerson, groupEntryDTO.voucherPerPerson);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupName, items, voucherPerPerson);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GroupEntryDTO {\n");
    
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("    voucherPerPerson: ").append(toIndentedString(voucherPerPerson)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

