/*
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bymdev.voucherhub.model;

import java.util.Objects;
import com.bymdev.voucherhub.model.DeliveryDTO;
import com.bymdev.voucherhub.model.GroupEntryDTO;
import com.bymdev.voucherhub.model.UserDTO;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * OrderRecordExtendDTO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T18:51:48.018+03:00")
public class OrderRecordExtendDTO {
  @SerializedName("amount")
  private Double amount = null;

  @SerializedName("cellPhoneNumber")
  private String cellPhoneNumber = null;

  @SerializedName("created")
  private String created = null;

  @SerializedName("createdBy")
  private UserDTO createdBy = null;

  @SerializedName("customerEmail")
  private String customerEmail = null;

  @SerializedName("customerId")
  private String customerId = null;

  @SerializedName("delivery")
  private DeliveryDTO delivery = null;

  /**
   * Gets or Sets deliveryMethod
   */
  @JsonAdapter(DeliveryMethodEnum.Adapter.class)
  public enum DeliveryMethodEnum {
    DIGITAL("DIGITAL"),
    
    SHIPPING("SHIPPING");

    private String value;

    DeliveryMethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DeliveryMethodEnum fromValue(String text) {
      for (DeliveryMethodEnum b : DeliveryMethodEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<DeliveryMethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DeliveryMethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DeliveryMethodEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return DeliveryMethodEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("deliveryMethod")
  private DeliveryMethodEnum deliveryMethod = null;

  @SerializedName("groups")
  private java.util.List<GroupEntryDTO> groups = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("isTest")
  private Boolean isTest = null;

  @SerializedName("isValidated")
  private Boolean isValidated = null;

  @SerializedName("orderId")
  private String orderId = null;

  @SerializedName("originatorOrderId")
  private String originatorOrderId = null;

  @SerializedName("originiator")
  private String originiator = null;

  @SerializedName("vendorOrderId")
  private String vendorOrderId = null;

  public OrderRecordExtendDTO amount(Double amount) {
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @ApiModelProperty(value = "")
  public Double getAmount() {
    return amount;
  }

  public void setAmount(Double amount) {
    this.amount = amount;
  }

  public OrderRecordExtendDTO cellPhoneNumber(String cellPhoneNumber) {
    this.cellPhoneNumber = cellPhoneNumber;
    return this;
  }

   /**
   * Get cellPhoneNumber
   * @return cellPhoneNumber
  **/
  @ApiModelProperty(value = "")
  public String getCellPhoneNumber() {
    return cellPhoneNumber;
  }

  public void setCellPhoneNumber(String cellPhoneNumber) {
    this.cellPhoneNumber = cellPhoneNumber;
  }

  public OrderRecordExtendDTO created(String created) {
    this.created = created;
    return this;
  }

   /**
   * Get created
   * @return created
  **/
  @ApiModelProperty(value = "")
  public String getCreated() {
    return created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public OrderRecordExtendDTO createdBy(UserDTO createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @ApiModelProperty(value = "")
  public UserDTO getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(UserDTO createdBy) {
    this.createdBy = createdBy;
  }

  public OrderRecordExtendDTO customerEmail(String customerEmail) {
    this.customerEmail = customerEmail;
    return this;
  }

   /**
   * Get customerEmail
   * @return customerEmail
  **/
  @ApiModelProperty(value = "")
  public String getCustomerEmail() {
    return customerEmail;
  }

  public void setCustomerEmail(String customerEmail) {
    this.customerEmail = customerEmail;
  }

  public OrderRecordExtendDTO customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

   /**
   * Get customerId
   * @return customerId
  **/
  @ApiModelProperty(value = "")
  public String getCustomerId() {
    return customerId;
  }

  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public OrderRecordExtendDTO delivery(DeliveryDTO delivery) {
    this.delivery = delivery;
    return this;
  }

   /**
   * Get delivery
   * @return delivery
  **/
  @ApiModelProperty(value = "")
  public DeliveryDTO getDelivery() {
    return delivery;
  }

  public void setDelivery(DeliveryDTO delivery) {
    this.delivery = delivery;
  }

  public OrderRecordExtendDTO deliveryMethod(DeliveryMethodEnum deliveryMethod) {
    this.deliveryMethod = deliveryMethod;
    return this;
  }

   /**
   * Get deliveryMethod
   * @return deliveryMethod
  **/
  @ApiModelProperty(value = "")
  public DeliveryMethodEnum getDeliveryMethod() {
    return deliveryMethod;
  }

  public void setDeliveryMethod(DeliveryMethodEnum deliveryMethod) {
    this.deliveryMethod = deliveryMethod;
  }

  public OrderRecordExtendDTO groups(java.util.List<GroupEntryDTO> groups) {
    this.groups = groups;
    return this;
  }

  public OrderRecordExtendDTO addGroupsItem(GroupEntryDTO groupsItem) {
    if (this.groups == null) {
      this.groups = new java.util.ArrayList<>();
    }
    this.groups.add(groupsItem);
    return this;
  }

   /**
   * Get groups
   * @return groups
  **/
  @ApiModelProperty(value = "")
  public java.util.List<GroupEntryDTO> getGroups() {
    return groups;
  }

  public void setGroups(java.util.List<GroupEntryDTO> groups) {
    this.groups = groups;
  }

  public OrderRecordExtendDTO id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public OrderRecordExtendDTO isTest(Boolean isTest) {
    this.isTest = isTest;
    return this;
  }

   /**
   * Get isTest
   * @return isTest
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsTest() {
    return isTest;
  }

  public void setIsTest(Boolean isTest) {
    this.isTest = isTest;
  }

  public OrderRecordExtendDTO isValidated(Boolean isValidated) {
    this.isValidated = isValidated;
    return this;
  }

   /**
   * Get isValidated
   * @return isValidated
  **/
  @ApiModelProperty(value = "")
  public Boolean isIsValidated() {
    return isValidated;
  }

  public void setIsValidated(Boolean isValidated) {
    this.isValidated = isValidated;
  }

  public OrderRecordExtendDTO orderId(String orderId) {
    this.orderId = orderId;
    return this;
  }

   /**
   * Get orderId
   * @return orderId
  **/
  @ApiModelProperty(value = "")
  public String getOrderId() {
    return orderId;
  }

  public void setOrderId(String orderId) {
    this.orderId = orderId;
  }

  public OrderRecordExtendDTO originatorOrderId(String originatorOrderId) {
    this.originatorOrderId = originatorOrderId;
    return this;
  }

   /**
   * Get originatorOrderId
   * @return originatorOrderId
  **/
  @ApiModelProperty(value = "")
  public String getOriginatorOrderId() {
    return originatorOrderId;
  }

  public void setOriginatorOrderId(String originatorOrderId) {
    this.originatorOrderId = originatorOrderId;
  }

  public OrderRecordExtendDTO originiator(String originiator) {
    this.originiator = originiator;
    return this;
  }

   /**
   * Get originiator
   * @return originiator
  **/
  @ApiModelProperty(value = "")
  public String getOriginiator() {
    return originiator;
  }

  public void setOriginiator(String originiator) {
    this.originiator = originiator;
  }

  public OrderRecordExtendDTO vendorOrderId(String vendorOrderId) {
    this.vendorOrderId = vendorOrderId;
    return this;
  }

   /**
   * Get vendorOrderId
   * @return vendorOrderId
  **/
  @ApiModelProperty(value = "")
  public String getVendorOrderId() {
    return vendorOrderId;
  }

  public void setVendorOrderId(String vendorOrderId) {
    this.vendorOrderId = vendorOrderId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OrderRecordExtendDTO orderRecordExtendDTO = (OrderRecordExtendDTO) o;
    return Objects.equals(this.amount, orderRecordExtendDTO.amount) &&
        Objects.equals(this.cellPhoneNumber, orderRecordExtendDTO.cellPhoneNumber) &&
        Objects.equals(this.created, orderRecordExtendDTO.created) &&
        Objects.equals(this.createdBy, orderRecordExtendDTO.createdBy) &&
        Objects.equals(this.customerEmail, orderRecordExtendDTO.customerEmail) &&
        Objects.equals(this.customerId, orderRecordExtendDTO.customerId) &&
        Objects.equals(this.delivery, orderRecordExtendDTO.delivery) &&
        Objects.equals(this.deliveryMethod, orderRecordExtendDTO.deliveryMethod) &&
        Objects.equals(this.groups, orderRecordExtendDTO.groups) &&
        Objects.equals(this.id, orderRecordExtendDTO.id) &&
        Objects.equals(this.isTest, orderRecordExtendDTO.isTest) &&
        Objects.equals(this.isValidated, orderRecordExtendDTO.isValidated) &&
        Objects.equals(this.orderId, orderRecordExtendDTO.orderId) &&
        Objects.equals(this.originatorOrderId, orderRecordExtendDTO.originatorOrderId) &&
        Objects.equals(this.originiator, orderRecordExtendDTO.originiator) &&
        Objects.equals(this.vendorOrderId, orderRecordExtendDTO.vendorOrderId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, cellPhoneNumber, created, createdBy, customerEmail, customerId, delivery, deliveryMethod, groups, id, isTest, isValidated, orderId, originatorOrderId, originiator, vendorOrderId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OrderRecordExtendDTO {\n");
    
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    cellPhoneNumber: ").append(toIndentedString(cellPhoneNumber)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    customerEmail: ").append(toIndentedString(customerEmail)).append("\n");
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    delivery: ").append(toIndentedString(delivery)).append("\n");
    sb.append("    deliveryMethod: ").append(toIndentedString(deliveryMethod)).append("\n");
    sb.append("    groups: ").append(toIndentedString(groups)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isTest: ").append(toIndentedString(isTest)).append("\n");
    sb.append("    isValidated: ").append(toIndentedString(isValidated)).append("\n");
    sb.append("    orderId: ").append(toIndentedString(orderId)).append("\n");
    sb.append("    originatorOrderId: ").append(toIndentedString(originatorOrderId)).append("\n");
    sb.append("    originiator: ").append(toIndentedString(originiator)).append("\n");
    sb.append("    vendorOrderId: ").append(toIndentedString(vendorOrderId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

