/*
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bymdev.voucherhub.model;

import java.util.Objects;
import com.bymdev.voucherhub.model.RechargePromptEntry;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RechargeProductGroup
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T14:17:27.430+03:00")
public class RechargeProductGroup {
  @SerializedName("entries")
  private java.util.List<RechargePromptEntry> entries = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("passProduct")
  private Boolean passProduct = null;

  @SerializedName("price")
  private Double price = null;

  @SerializedName("productIds")
  private java.util.List<Long> productIds = null;

  @SerializedName("productTag")
  private String productTag = null;

  public RechargeProductGroup entries(java.util.List<RechargePromptEntry> entries) {
    this.entries = entries;
    return this;
  }

  public RechargeProductGroup addEntriesItem(RechargePromptEntry entriesItem) {
    if (this.entries == null) {
      this.entries = new java.util.ArrayList<>();
    }
    this.entries.add(entriesItem);
    return this;
  }

   /**
   * Get entries
   * @return entries
  **/
  @ApiModelProperty(value = "")
  public java.util.List<RechargePromptEntry> getEntries() {
    return entries;
  }

  public void setEntries(java.util.List<RechargePromptEntry> entries) {
    this.entries = entries;
  }

  public RechargeProductGroup name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RechargeProductGroup passProduct(Boolean passProduct) {
    this.passProduct = passProduct;
    return this;
  }

   /**
   * Get passProduct
   * @return passProduct
  **/
  @ApiModelProperty(value = "")
  public Boolean isPassProduct() {
    return passProduct;
  }

  public void setPassProduct(Boolean passProduct) {
    this.passProduct = passProduct;
  }

  public RechargeProductGroup price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  @ApiModelProperty(value = "")
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }

  public RechargeProductGroup productIds(java.util.List<Long> productIds) {
    this.productIds = productIds;
    return this;
  }

  public RechargeProductGroup addProductIdsItem(Long productIdsItem) {
    if (this.productIds == null) {
      this.productIds = new java.util.ArrayList<>();
    }
    this.productIds.add(productIdsItem);
    return this;
  }

   /**
   * Get productIds
   * @return productIds
  **/
  @ApiModelProperty(value = "")
  public java.util.List<Long> getProductIds() {
    return productIds;
  }

  public void setProductIds(java.util.List<Long> productIds) {
    this.productIds = productIds;
  }

  public RechargeProductGroup productTag(String productTag) {
    this.productTag = productTag;
    return this;
  }

   /**
   * Get productTag
   * @return productTag
  **/
  @ApiModelProperty(value = "")
  public String getProductTag() {
    return productTag;
  }

  public void setProductTag(String productTag) {
    this.productTag = productTag;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RechargeProductGroup rechargeProductGroup = (RechargeProductGroup) o;
    return Objects.equals(this.entries, rechargeProductGroup.entries) &&
        Objects.equals(this.name, rechargeProductGroup.name) &&
        Objects.equals(this.passProduct, rechargeProductGroup.passProduct) &&
        Objects.equals(this.price, rechargeProductGroup.price) &&
        Objects.equals(this.productIds, rechargeProductGroup.productIds) &&
        Objects.equals(this.productTag, rechargeProductGroup.productTag);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entries, name, passProduct, price, productIds, productTag);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RechargeProductGroup {\n");
    
    sb.append("    entries: ").append(toIndentedString(entries)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    passProduct: ").append(toIndentedString(passProduct)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    productIds: ").append(toIndentedString(productIds)).append("\n");
    sb.append("    productTag: ").append(toIndentedString(productTag)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

