/*
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bymdev.voucherhub.model;

import java.util.Objects;
import com.bymdev.voucherhub.model.RechargeProductGroup;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RechargePrompt
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T14:17:27.430+03:00")
public class RechargePrompt {
  @SerializedName("products")
  private java.util.List<RechargeProductGroup> products = null;

  @SerializedName("validationIds")
  private java.util.List<Long> validationIds = null;

  public RechargePrompt products(java.util.List<RechargeProductGroup> products) {
    this.products = products;
    return this;
  }

  public RechargePrompt addProductsItem(RechargeProductGroup productsItem) {
    if (this.products == null) {
      this.products = new java.util.ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/
  @ApiModelProperty(value = "")
  public java.util.List<RechargeProductGroup> getProducts() {
    return products;
  }

  public void setProducts(java.util.List<RechargeProductGroup> products) {
    this.products = products;
  }

  public RechargePrompt validationIds(java.util.List<Long> validationIds) {
    this.validationIds = validationIds;
    return this;
  }

  public RechargePrompt addValidationIdsItem(Long validationIdsItem) {
    if (this.validationIds == null) {
      this.validationIds = new java.util.ArrayList<>();
    }
    this.validationIds.add(validationIdsItem);
    return this;
  }

   /**
   * Get validationIds
   * @return validationIds
  **/
  @ApiModelProperty(value = "")
  public java.util.List<Long> getValidationIds() {
    return validationIds;
  }

  public void setValidationIds(java.util.List<Long> validationIds) {
    this.validationIds = validationIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RechargePrompt rechargePrompt = (RechargePrompt) o;
    return Objects.equals(this.products, rechargePrompt.products) &&
        Objects.equals(this.validationIds, rechargePrompt.validationIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(products, validationIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RechargePrompt {\n");
    
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    validationIds: ").append(toIndentedString(validationIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

