/*
 * PassHub API
 * PassHub API documentation
 *
 * OpenAPI spec version: 1.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.bymdev.voucherhub.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * VoucherPattern
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-06-21T18:51:48.018+03:00")
public class VoucherPattern {
  @SerializedName("bodyLength")
  private Integer bodyLength = null;

  /**
   * Gets or Sets bodyType
   */
  @JsonAdapter(BodyTypeEnum.Adapter.class)
  public enum BodyTypeEnum {
    NUMERIC("NUMERIC"),
    
    ALPHA_NUMERIC("ALPHA_NUMERIC");

    private String value;

    BodyTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static BodyTypeEnum fromValue(String text) {
      for (BodyTypeEnum b : BodyTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<BodyTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final BodyTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public BodyTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return BodyTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("bodyType")
  private BodyTypeEnum bodyType = null;

  @SerializedName("patternProductId")
  private Long patternProductId = null;

  @SerializedName("prefix")
  private String prefix = null;

  public VoucherPattern bodyLength(Integer bodyLength) {
    this.bodyLength = bodyLength;
    return this;
  }

   /**
   * Get bodyLength
   * @return bodyLength
  **/
  @ApiModelProperty(value = "")
  public Integer getBodyLength() {
    return bodyLength;
  }

  public void setBodyLength(Integer bodyLength) {
    this.bodyLength = bodyLength;
  }

  public VoucherPattern bodyType(BodyTypeEnum bodyType) {
    this.bodyType = bodyType;
    return this;
  }

   /**
   * Get bodyType
   * @return bodyType
  **/
  @ApiModelProperty(value = "")
  public BodyTypeEnum getBodyType() {
    return bodyType;
  }

  public void setBodyType(BodyTypeEnum bodyType) {
    this.bodyType = bodyType;
  }

  public VoucherPattern patternProductId(Long patternProductId) {
    this.patternProductId = patternProductId;
    return this;
  }

   /**
   * Get patternProductId
   * @return patternProductId
  **/
  @ApiModelProperty(value = "")
  public Long getPatternProductId() {
    return patternProductId;
  }

  public void setPatternProductId(Long patternProductId) {
    this.patternProductId = patternProductId;
  }

  public VoucherPattern prefix(String prefix) {
    this.prefix = prefix;
    return this;
  }

   /**
   * Get prefix
   * @return prefix
  **/
  @ApiModelProperty(value = "")
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(String prefix) {
    this.prefix = prefix;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VoucherPattern voucherPattern = (VoucherPattern) o;
    return Objects.equals(this.bodyLength, voucherPattern.bodyLength) &&
        Objects.equals(this.bodyType, voucherPattern.bodyType) &&
        Objects.equals(this.patternProductId, voucherPattern.patternProductId) &&
        Objects.equals(this.prefix, voucherPattern.prefix);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bodyLength, bodyType, patternProductId, prefix);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VoucherPattern {\n");
    
    sb.append("    bodyLength: ").append(toIndentedString(bodyLength)).append("\n");
    sb.append("    bodyType: ").append(toIndentedString(bodyType)).append("\n");
    sb.append("    patternProductId: ").append(toIndentedString(patternProductId)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

